Initial manuscript submission

diff --git a/draft/Makefile b/draft/Makefile
--- a/draft/Makefile
+++ b/draft/Makefile
@@ -1,180 +1,138 @@
 # Top-level dirs
 PROJECT_ROOT := $(realpath $(dir $(lastword $(MAKEFILE_LIST)))/..)
-R := $(PROJECT_ROOT)/R
-PYTHON := $(PROJECT_ROOT)/python
-DRAFT := $(PROJECT_ROOT)/draft
+R            := $(PROJECT_ROOT)/R
+PYTHON       := $(PROJECT_ROOT)/python
+DRAFT        := $(PROJECT_ROOT)/draft
 
-# Manuscript
-TEMPLATE := $(DRAFT)/eisvogel.tex
-YAML := $(DRAFT)/eisvogel.yaml
-SI_YAML := $(DRAFT)/eisvogel-si.yaml
-# TEMPLATE := $(DRAFT)/agu.tex
-# YAML := $(DRAFT)/agu.yaml
-# SI_YAML := $(DRAFT)/agu-si.yaml
-CSL := $(DRAFT)/agu.csl
-BIB := $(DRAFT)/main.bib
-DOC := $(DRAFT)/manuscript
-SI := $(DRAFT)/supplementary-information
-PREV_DOC := $(DRAFT)/bak/manuscript-24-nov-2025
-DIFF_DOC := $(DRAFT)/diff
+# Templates
+TEMPLATE      := $(DRAFT)/agu.tex
+TEMPLATE_NAME := $(notdir $(TEMPLATE))
+BIB           := $(DRAFT)/main.bib
+
+ifeq ($(TEMPLATE_NAME),agu.tex)
+    CFG_YAML      := $(DRAFT)/agu.yaml
+    CFG_SI_YAML   := $(DRAFT)/agu-si.yaml
+    CFG_SI_TPL    := $(DRAFT)/agu-si.tex
+    CFG_EXTRA     := --natbib
+else ifeq ($(TEMPLATE_NAME),eisvogel.tex)
+    CFG_YAML      := $(DRAFT)/eisvogel.yaml
+    CFG_SI_YAML   := $(DRAFT)/eisvogel.yaml
+    CFG_SI_TPL    := $(TEMPLATE)
+    CFG_EXTRA     := --citeproc --csl=$(DRAFT)/agu.csl --pdf-engine=pdflatex
+endif
+
+# Configure pandoc
+BASE_PANDOC_FLAGS := --from markdown --filter pandoc-crossref $(PANDOC_FLAGS)
+
+$(DRAFT)/manuscript.%: TPL                      := $(TEMPLATE)
+$(DRAFT)/manuscript.%: META                     := $(CFG_YAML)
+$(DRAFT)/manuscript.%: BIB_FLAG                 := --bibliography=$(BIB)
+
+$(DRAFT)/supplementary-information.%: TPL       := $(CFG_SI_TPL)
+$(DRAFT)/supplementary-information.%: META      := $(CFG_SI_YAML)
+$(DRAFT)/supplementary-information.%: BIB_FLAG  :=
+
+$(DRAFT)/diff-manuscript.%: META                := $(CFG_YAML)
+$(DRAFT)/diff-supplementary-information.%: META := $(CFG_SI_YAML)
+
+$(DRAFT)/response.%: TPL                        :=
+$(DRAFT)/response.%: META                       := $(DRAFT)/response.yaml
+$(DRAFT)/response.%: BIB_FLAG                   :=
+
+TPL_FLAG  = $(if $(TPL),--template=$(TPL))
+META_FLAG = $(if $(META),--metadata-file=$(META))
+PANDOC_FLAGS = --standalone --from=markdown --filter=pandoc-crossref $(CFG_EXTRA) $(TPL_FLAG) $(BIB_FLAG) $(META_FLAG)
+
+# Rendered files
+DOCS := manuscript supplementary-information
+PDFS := $(addprefix $(DRAFT)/, $(addsuffix .pdf, $(DOCS)))
+
+# Configure pdflatex
+PDFLATEX = pdflatex -interaction=nonstopmode -shell-escape -output-directory $(DRAFT)
+
+# Configure latexdiff
+BACKUP_DATE ?= 31-mar-2026
+DIFF_FLAGS = --flatten --math-markup=0 --type=CFONT --graphics-markup=none --exclude-textcmd="ref,eqref,label" --add-to-config PICTUREENV=longtable --config="ARRENV=thebibliography|APACrefauthors"
 
 # Cleanup targets
-CLEAN := $(DOC).{tex,pdf,aux,bbl,blg,log,toc} $(DIFF_DOC).{tex,pdf,aux,bbl,blg,log,toc} $(SI).{tex,pdf,aux,bbl,blg,log,toc}
+EXTS       := aux bbl blg log toc out tex pdf
+CLEAN      := $(foreach doc,$(DOCS) $(addprefix diff-,$(DOCS)),$(addprefix $(DRAFT)/$(doc).,$(EXTS))) $(addprefix $(DRAFT)/response.,$(EXTS))
 DEEP_CLEAN := $(PROJECT_ROOT)/figs
 
+# Prevent make from deleting .tex files on failure
+.PRECIOUS: $(DRAFT)/%.tex
+
 # Targets
-.PHONY: all diff manuscript supp update-date clean deep-clean help
+.PHONY: all diff clean deep-clean help
 
-all: manuscript supp
+all: $(PDFS)
+diff: all $(DRAFT)/diff-manuscript.pdf $(DRAFT)/diff-supplementary-information.pdf $(DRAFT)/response.pdf
 
-diff: $(DIFF_DOC).pdf
-
-manuscript: $(DOC).tex $(DOC).pdf
-
-supp: $(SI).tex $(SI).pdf
-
-$(DIFF_DOC).pdf: $(PREV_DOC).tex $(DOC).tex
-	@echo "    --------------------------------------------------"
-	@echo "    Rendering diff"
-	@echo "    --------------------------------------------------"
-	@echo " -> Comparing $(shell basename $(PREV_DOC).tex) with $(shell basename $(DOC).tex)"
-	@latexdiff \
-	  --flatten \
-	  --math-markup=0 \
-	  --type=CFONT \
-	  --add-to-config PICTUREENV=longtable \
-	  --graphics-markup=none \
-	  $(PREV_DOC).tex $(DOC).tex > $(DIFF_DOC).tex 2> /dev/null
-	@echo " -> Rendering $(shell basename $(DIFF_DOC).pdf) from $(shell basename $(DIFF_DOC).tex)"
-	@pdflatex -interaction=nonstopmode -shell-escape -output-directory $(DRAFT) $(DIFF_DOC).tex > /dev/null 2>&1 || true
-	@pdflatex -interaction=nonstopmode -shell-escape -output-directory $(DRAFT) $(DIFF_DOC).tex > /dev/null 2>&1 || true
-
-$(DOC).pdf: update-date
-	@echo " -> Rendering $(shell basename $(DOC).pdf) from $(shell basename $(DOC).tex)"
-	@if [ "$(shell basename $(TEMPLATE))" = "eisvogel.tex" ]; then \
-	  pandoc "$(DOC).md" -o "$(DOC).pdf" \
-	    --from markdown \
-	    --template "$(TEMPLATE)" \
-	    --metadata-file=$(YAML) \
-	    --bibliography=$(BIB) \
-	    --csl=$(CSL) \
-	    --filter=pandoc-crossref \
-	    --citeproc \
-	    --pdf-engine=pdflatex \
-	    --pdf-engine-opt="-shell-escape" \
-	    --pdf-engine-opt="-interaction=nonstopmode"; \
+$(DRAFT)/%.pdf: $(DRAFT)/%.tex
+	@echo " -> $@"
+	@if [ "$(TEMPLATE_NAME)" = "eisvogel.tex" ]; then \
+	  @pandoc $(subst .tex,.md,$<) -o $@ $(PANDOC_FLAGS); \
 	else \
-	  pdflatex -interaction=nonstopmode -shell-escape -output-directory $(DRAFT) $(DOC).tex > /dev/null 2>&1 || true; \
-	  cd $(DRAFT) && bibtex $(notdir $(DOC)) > /dev/null 2>&1; \
-	  pdflatex -interaction=nonstopmode -shell-escape -output-directory $(DRAFT) $(DOC).tex > /dev/null 2>&1 || true; \
-	  pdflatex -interaction=nonstopmode -shell-escape -output-directory $(DRAFT) $(DOC).tex > /dev/null 2>&1 || true; \
+	  $(PDFLATEX) $< > /dev/null 2>&1; \
+	  cd $(DRAFT) && bibtex $(notdir $*) > /dev/null 2>&1; \
+	  $(PDFLATEX) $< > /dev/null 2>&1; \
+	  $(PDFLATEX) $< > /dev/null 2>&1; \
 	fi
 
-$(SI).pdf: update-date
-	@echo " -> Rendering $(shell basename $(SI).pdf) from $(shell basename $(SI).tex)"
-	@if [ "$(shell basename $(TEMPLATE))" = "eisvogel.tex" ]; then \
-	  pandoc "$(SI).md" -o "$(SI).pdf" \
-	    --from markdown \
-	    --template "$(TEMPLATE)" \
-	    --metadata-file=$(SI_YAML) \
-	    --bibliography=$(BIB) \
-	    --csl=$(CSL) \
-	    --filter=pandoc-crossref \
-	    --citeproc \
-	    --pdf-engine=pdflatex \
-	    --pdf-engine-opt="-shell-escape" \
-	    --pdf-engine-opt="-interaction=nonstopmode"; \
-	else \
-	  pdflatex -interaction=nonstopmode -shell-escape -output-directory $(DRAFT) $(SI).tex > /dev/null 2>&1 || true; \
-	  cd $(DRAFT) && bibtex $(notdir $(SI)) > /dev/null 2>&1; \
-	  pdflatex -interaction=nonstopmode -shell-escape -output-directory $(DRAFT) $(SI).tex > /dev/null 2>&1 || true; \
-	  pdflatex -interaction=nonstopmode -shell-escape -output-directory $(DRAFT) $(SI).tex > /dev/null 2>&1 || true; \
-	fi
+$(DRAFT)/bak/%.tex: ;
 
-$(DOC).tex: update-date
-	@echo "    --------------------------------------------------"
-	@echo "    Rendering manuscript"
-	@echo "    --------------------------------------------------"
-	@echo " -> Rendering $(shell basename $(DOC).tex) from $(shell basename $(DOC).md) with $(shell basename $(TEMPLATE)) template"
-	@if [ "$(shell basename $(TEMPLATE))" = "eisvogel.tex" ]; then \
-	  pandoc "$(DOC).md" -s -o "$(DOC).tex" \
-	    --from markdown \
-	    --template "$(TEMPLATE)" \
-	    --metadata-file=$(YAML) \
-	    --bibliography=$(BIB) \
-	    --csl=$(CSL) \
-	    --filter=pandoc-crossref \
-	    --citeproc; \
-	else \
-	  pandoc "$(DOC).md" -o "$(DOC).tex" \
-	    --from markdown \
-	    --template "$(TEMPLATE)" \
-	    --metadata-file=$(YAML) \
-	    --bibliography=$(BIB) \
-	    --filter=pandoc-crossref \
-	    --natbib; \
-	fi
+$(DRAFT)/%.tex: $(DRAFT)/%.md
+	@echo " -> $@"
+	@$(if $(META),sed -i '' -E "s/^date: \".*\"/date: \"$(shell date '+%d %B %Y')\"/" $(META))
+	@pandoc $< -o $@ $(PANDOC_FLAGS)
 
-$(SI).tex: update-date
-	@echo "    --------------------------------------------------"
-	@echo "    Rendering supplementary information"
-	@echo "    --------------------------------------------------"
-	@echo " -> Rendering $(shell basename $(SI).tex) from $(shell basename $(SI).md) with $(shell basename $(TEMPLATE)) template"
-	@if [ "$(shell basename $(TEMPLATE))" = "eisvogel.tex" ]; then \
-	  pandoc "$(SI).md" -s -o "$(SI).tex" \
-	    --from markdown \
-	    --template "$(TEMPLATE)" \
-	    --metadata-file=$(SI_YAML) \
-	    --bibliography=$(BIB) \
-	    --csl=$(CSL) \
-	    --filter=pandoc-crossref \
-	    --citeproc; \
-	else \
-	  pandoc "$(SI).md" -o "$(SI).tex" \
-	    --from markdown \
-	    --template agu-si.tex \
-	    --metadata-file=$(SI_YAML) \
-	    --bibliography=$(BIB) \
-	    --csl=$(CSL) \
-	    --filter=pandoc-crossref \
-	    --natbib; \
+$(DRAFT)/diff-%.pdf: $(DRAFT)/bak/%-$(BACKUP_DATE).tex $(DRAFT)/%.tex
+	@echo " -> $@ [bak: $(BACKUP_DATE)]"
+	@if [ ! -f "$<" ]; then \
+	  echo "Error: Backup file $< not found!"; \
+	  exit 1; \
 	fi
-
-update-date:
-	@sed -i '' -E "s/^date: \".*\"/date: \"$(shell date '+%d %B %Y')\"/" $(DOC).md
+	@latexdiff $(DIFF_FLAGS) $< $(word 2,$^) > $(DRAFT)/diff-$*.tex
+	@cp $(DRAFT)/$*.bbl $(DRAFT)/diff-$*.bbl || true
+	@cp $(DRAFT)/$*.aux $(DRAFT)/diff-$*.aux || true
+	@$(PDFLATEX) $(DRAFT)/diff-$*.tex > /dev/null 2>&1
+	@$(PDFLATEX) $(DRAFT)/diff-$*.tex > /dev/null 2>&1
 
 clean:
 	@for item in $(CLEAN); do \
-		safe_rm() { \
-			if [ -e "$$1" ]; then \
-				ABS_PATH=$$(realpath "$$1"); \
-				if [[ "$$ABS_PATH" == $(PROJECT_ROOT)* ]]; then \
-					echo " -> Safely removing: $$ABS_PATH"; \
-					rm -rf "$$ABS_PATH"; \
-				fi; \
-			fi; \
-		}; \
-		safe_rm "$$item"; \
+	  safe_rm() { \
+	    if [ -e "$$1" ]; then \
+	      ABS_PATH=$$(realpath "$$1"); \
+	      if [[ "$$ABS_PATH" == $(PROJECT_ROOT)* ]]; then \
+	        echo " xx $$ABS_PATH"; \
+	        rm -rf "$$ABS_PATH"; \
+	      fi; \
+	    fi; \
+	  }; \
+	  safe_rm "$$item"; \
 	done
 
 deep-clean:
 	@for item in $(DEEP_CLEAN); do \
-		safe_rm() { \
-			if [ -e "$$1" ]; then \
-				ABS_PATH=$$(realpath "$$1"); \
-				if [[ "$$ABS_PATH" == $(PROJECT_ROOT)* ]]; then \
-					echo " -> Safely removing: $$ABS_PATH"; \
-					rm -rf "$$ABS_PATH"; \
-				fi; \
-			fi; \
-		}; \
-		safe_rm "$$item"; \
+	  safe_rm() { \
+	    if [ -e "$$1" ]; then \
+	      ABS_PATH=$$(realpath "$$1"); \
+	      if [[ "$$ABS_PATH" == $(PROJECT_ROOT)* ]]; then \
+	        echo " xx $$ABS_PATH"; \
+	        rm -rf "$$ABS_PATH"; \
+	      fi; \
+	    fi; \
+	  }; \
+	  safe_rm "$$item"; \
 	done
 
 help:
 	@echo "    --------------------------------------------------"
 	@echo "    Available targets:"
 	@echo "    --------------------------------------------------"
-	@echo "    clean       Cleanup unnecessary files and directories (safe)"
-	@echo "    deep-clean  Deep clean figures and results (use with caution!)"
-	@echo "    help        Show this help message"
+	@echo "    all                                Render manuscript and SI"
+	@echo "    diff-manuscript.pdf                Generate manuscript diff"
+	@echo "    diff-supplementary-information.pdf Generate SI diff"
+	@echo "    clean                              Cleanup unnecessary files"
+	@echo "    --------------------------------------------------"
+	@echo "    Note: Use BACKUP_DATE=DD-MMM-YYYY to change diff source."
